import smtplib
import os
from email.mime.text import MimeText
from email.mime.multipart import MimeMultipart
from email.mime.application import MIMEApplication

class EmailSender:
    def __init__(self):
        self.sender_email = os.getenv('SENDER_EMAIL')
        self.sender_password = os.getenv('SENDER_PASSWORD')
        self.receiver_email = os.getenv('RECEIVER_EMAIL')
    
    def send_research_email(self, paper, summary, difficulty, pdf_path):
        # Tạo email message
        message = MimeMultipart()
        message["From"] = self.sender_email
        message["To"] = self.receiver_email
        message["Subject"] = f"🧠 [{paper['category']}] {difficulty} - {paper['title'][:50]}..."
        
        # Email body
        body = f"""
<h2>🎯 Research Digest for Software Engineer</h2>

<p><strong>Chủ đề:</strong> {paper['category']} | <strong>Độ khó:</strong> {difficulty}</p>
<p><strong>Bài báo:</strong> {paper['title']}</p>

<hr>

<div style="background: #f8f9fa; padding: 15px; border-radius: 8px;">
{summary.replace('\n', '<br>')}
</div>

<hr>

<p><strong>📚 Full Paper:</strong> <a href="{paper['pdf_url']}">{paper['pdf_url']}</a></p>
<p><strong>👨‍💻 Tác giả:</strong> {', '.join(paper['authors'][:3])}</p>

<p><em>---<br>
🤖 Auto-generated by Research Digest Bot<br>
Feedback? Reply this email!</em></p>
"""
        
        message.attach(MimeText(body, "html"))
        
        # Đính kèm PDF
        with open(pdf_path, "rb") as f:
            pdf_attachment = MIMEApplication(f.read(), _subtype="pdf")
            pdf_attachment.add_header('Content-Disposition', 'attachment', 
                                    filename=f"Research_{paper['category']}_{difficulty}.pdf")
            message.attach(pdf_attachment)
        
        # Gửi email
        try:
            with smtplib.SMTP("smtp.gmail.com", 587) as server:
                server.starttls()
                server.login(self.sender_email, self.sender_password)
                server.send_message(message)
            return True
        except Exception as e:
            print(f"❌ Lỗi gửi email: {e}")
            return False