name: Daily Research Email
on:
  schedule:
    - cron: '0 1 * * 1-5'
  workflow_dispatch:

jobs:
  send-research-email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install feedparser requests fpdf2 python-dotenv beautifulsoup4 google-generativeai
          
      - name: Debug Secrets
        run: |
          echo "Secrets check:"
          echo "GEMINI length: ${#GEMINI_API_KEY}"
          echo "SENDER_EMAIL: $SENDER_EMAIL"
          echo "RECEIVER_EMAIL: $RECEIVER_EMAIL"
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          
      - name: Run Pipeline
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: |
          cd src
          python main.py